### ISSUE TITLE
Catching

### ISSUE THREAD

**Issue by kyledovey** [jextious/pokengine#37]
How is this not already in here...

**Comment by varkor** [comment]
I think it's not included because https://github.com/jextious/pokengine/issues/8 effectively covers it.

**Comment by kyledovey** [comment]
Seeing as DM was able to catch a Stethoscale and add it to his team, I guess we can now close this off.

**Comment by varkor** [comment]
It only added it temporarily—new Pokémon don't save yet.

**Comment by kyledovey** [comment]
They definitely save now!
